# Generated by Django 6.0.2 on 2026-03-14 04:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('exchange', models.CharField(choices=[('NYSE', 'New York Stock Exchange'), ('NASDAQ', 'NASDAQ'), ('SET', 'Stock Exchange of Thailand'), ('LSE', 'London Stock Exchange'), ('TSE', 'Tokyo Stock Exchange'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('sector', models.CharField(blank=True, db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Symbol',
                'verbose_name_plural': 'Symbols',
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['exchange', 'sector'], name='idx_symbol_exchange_sector')],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('BUY', 'Buy'), ('STRONG_BUY', 'Strong Buy'), ('BREAKOUT', 'Breakout'), ('GOLDEN_CROSS', 'Golden Cross'), ('OVERSOLD', 'Oversold / RSI bounce'), ('SELL', 'Sell'), ('STRONG_SELL', 'Strong Sell'), ('BREAKDOWN', 'Breakdown'), ('DEATH_CROSS', 'Death Cross'), ('OVERBOUGHT', 'Overbought / RSI fade'), ('WATCH', 'Watch'), ('ALERT', 'Alert')], db_index=True, max_length=20)),
                ('score', models.DecimalField(db_index=True, decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='radar.symbol')),
            ],
            options={
                'verbose_name': 'Signal',
                'verbose_name_plural': 'Signals',
                'ordering': ['-created_at', '-score'],
                'indexes': [models.Index(fields=['symbol', '-created_at', '-score'], name='idx_signal_symbol_recent_score'), models.Index(fields=['signal_type', '-created_at', '-score'], name='idx_signal_type_recent_score'), models.Index(fields=['-score', '-created_at'], name='idx_signal_score_recent')],
            },
        ),
        migrations.CreateModel(
            name='PriceDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=18)),
                ('high', models.DecimalField(decimal_places=4, max_digits=18)),
                ('low', models.DecimalField(decimal_places=4, max_digits=18)),
                ('close', models.DecimalField(decimal_places=4, max_digits=18)),
                ('volume', models.BigIntegerField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='radar.symbol')),
            ],
            options={
                'verbose_name': 'Daily Price',
                'verbose_name_plural': 'Daily Prices',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['symbol', '-date'], name='idx_price_symbol_date_desc'), models.Index(fields=['date'], name='idx_price_date')],
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('rsi', models.DecimalField(blank=True, decimal_places=2, help_text='Relative Strength Index (0–100)', max_digits=6, null=True)),
                ('ema20', models.DecimalField(blank=True, decimal_places=4, help_text='20-day EMA', max_digits=18, null=True)),
                ('ema50', models.DecimalField(blank=True, decimal_places=4, help_text='50-day EMA', max_digits=18, null=True)),
                ('ema200', models.DecimalField(blank=True, decimal_places=4, help_text='200-day EMA', max_digits=18, null=True)),
                ('volume_avg30', models.BigIntegerField(blank=True, help_text='30-day average daily volume', null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='radar.symbol')),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicators',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['symbol', '-date'], name='idx_indicator_symbol_date_desc'), models.Index(fields=['date', 'rsi'], name='idx_indicator_date_rsi'), models.Index(fields=['date', 'ema20', 'ema50'], name='idx_indicator_date_ema_cross')],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
