# Generated by Django 6.0.2 on 2026-03-14 12:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricedaily',
            options={'ordering': ['-date'], 'verbose_name': 'ราคารายวัน', 'verbose_name_plural': 'ราคารายวัน'},
        ),
        migrations.AlterModelOptions(
            name='signal',
            options={'ordering': ['-created_at', '-score'], 'verbose_name': 'สัญญาณ', 'verbose_name_plural': 'สัญญาณซื้อขาย'},
        ),
        migrations.AlterModelOptions(
            name='symbol',
            options={'ordering': ['symbol'], 'verbose_name': 'หุ้น', 'verbose_name_plural': 'รายชื่อหุ้น'},
        ),
        migrations.AddField(
            model_name='indicator',
            name='bb_lower',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='BB Lower'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='bb_middle',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='BB Middle'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='bb_upper',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='BB Upper'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='macd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='EMA12 - EMA26', max_digits=18, null=True, verbose_name='MACD Line'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='macd_hist',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='MACD Histogram'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='macd_signal',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='EMA9 ของ MACD', max_digits=18, null=True, verbose_name='MACD Signal'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='date',
            field=models.DateField(db_index=True, verbose_name='วันที่'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='ema20',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='EMA 20'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='ema200',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='EMA 200'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='ema50',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='EMA 50'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='rsi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0–100', max_digits=6, null=True, verbose_name='RSI 14'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='radar.symbol', verbose_name='หุ้น'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='volume_avg30',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Volume เฉลี่ย 30 วัน'),
        ),
        migrations.AlterField(
            model_name='pricedaily',
            name='close',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='ปิด'),
        ),
        migrations.AlterField(
            model_name='pricedaily',
            name='date',
            field=models.DateField(db_index=True, verbose_name='วันที่'),
        ),
        migrations.AlterField(
            model_name='pricedaily',
            name='high',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='สูงสุด'),
        ),
        migrations.AlterField(
            model_name='pricedaily',
            name='low',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='ต่ำสุด'),
        ),
        migrations.AlterField(
            model_name='pricedaily',
            name='open',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='เปิด'),
        ),
        migrations.AlterField(
            model_name='pricedaily',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='radar.symbol', verbose_name='หุ้น'),
        ),
        migrations.AlterField(
            model_name='pricedaily',
            name='volume',
            field=models.BigIntegerField(verbose_name='ปริมาณ'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='เวลาที่สร้าง'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='ราคา ณ เวลาสัญญาณ'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='score',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=6, verbose_name='คะแนน (0–100)'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='signal_type',
            field=models.CharField(choices=[('BUY', 'ซื้อ'), ('STRONG_BUY', 'ซื้อแข็งแกร่ง'), ('BREAKOUT', 'Breakout'), ('GOLDEN_CROSS', 'Golden Cross'), ('OVERSOLD', 'Oversold / RSI ต่ำ'), ('SELL', 'ขาย'), ('STRONG_SELL', 'ขายแข็งแกร่ง'), ('BREAKDOWN', 'Breakdown'), ('DEATH_CROSS', 'Death Cross'), ('OVERBOUGHT', 'Overbought / RSI สูง'), ('WATCH', 'เฝ้าดู'), ('ALERT', 'แจ้งเตือน')], db_index=True, max_length=20, verbose_name='ประเภทสัญญาณ'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='radar.symbol', verbose_name='หุ้น'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='exchange',
            field=models.CharField(choices=[('SET', 'ตลาดหลักทรัพย์แห่งประเทศไทย'), ('NASDAQ', 'NASDAQ'), ('NYSE', 'New York Stock Exchange'), ('OTHER', 'อื่นๆ')], db_index=True, max_length=20, verbose_name='ตลาด'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ชื่อบริษัท'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='sector',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='หมวดอุตสาหกรรม'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='symbol',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='รหัสหุ้น'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['date', 'macd_hist'], name='idx_indicator_date_macd_hist'),
        ),
    ]
