# Generated by Django 6.0.2 on 2026-03-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0002_alter_pricedaily_options_alter_signal_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='indicator',
            new_name='idx_ind_symbol_date',
            old_name='idx_indicator_symbol_date_desc',
        ),
        migrations.RenameIndex(
            model_name='indicator',
            new_name='idx_ind_date_rsi',
            old_name='idx_indicator_date_rsi',
        ),
        migrations.RenameIndex(
            model_name='indicator',
            new_name='idx_ind_date_ema_cross',
            old_name='idx_indicator_date_ema_cross',
        ),
        migrations.RenameIndex(
            model_name='indicator',
            new_name='idx_ind_date_macd',
            old_name='idx_indicator_date_macd_hist',
        ),
        migrations.RenameIndex(
            model_name='signal',
            new_name='idx_sig_symbol_recent',
            old_name='idx_signal_symbol_recent_score',
        ),
        migrations.RenameIndex(
            model_name='signal',
            new_name='idx_sig_type_recent',
            old_name='idx_signal_type_recent_score',
        ),
        migrations.RenameIndex(
            model_name='signal',
            new_name='idx_sig_score_recent',
            old_name='idx_signal_score_recent',
        ),
        migrations.AddField(
            model_name='indicator',
            name='adx14',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Trend Strength 0–100 (>25 = แนวโน้มชัด)', max_digits=6, null=True, verbose_name='ADX 14'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='atr14',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Wilder ATR 14 วัน — วัดความผันผวน', max_digits=18, null=True, verbose_name='ATR 14'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='atr_avg30',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='ค่าเฉลี่ย ATR 30 วัน — Volatility Filter', max_digits=18, null=True, verbose_name='ATR Avg 30'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='di_minus',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Negative Directional Indicator', max_digits=6, null=True, verbose_name='-DI 14'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='di_plus',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Positive Directional Indicator', max_digits=6, null=True, verbose_name='+DI 14'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='highest_high_20',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='ราคาสูงสุดใน 20 วัน — Breakout signal', max_digits=18, null=True, verbose_name='Highest High 20'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='lowest_low_20',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='ราคาต่ำสุดใน 20 วัน — Breakdown signal', max_digits=18, null=True, verbose_name='Lowest Low 20'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='volume_avg20',
            field=models.BigIntegerField(blank=True, help_text='Volume เฉลี่ย 20 วัน — Volume Filter (>1.5×)', null=True, verbose_name='Volume Avg 20'),
        ),
        migrations.AddField(
            model_name='signal',
            name='adx_at_signal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='ADX'),
        ),
        migrations.AddField(
            model_name='signal',
            name='atr_at_signal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='ATR'),
        ),
        migrations.AddField(
            model_name='signal',
            name='direction',
            field=models.CharField(choices=[('LONG', 'Long / ซื้อ'), ('SHORT', 'Short / ขาย'), ('NEUTRAL', 'Neutral')], db_index=True, default='NEUTRAL', max_length=10, verbose_name='ทิศทาง'),
        ),
        migrations.AddField(
            model_name='signal',
            name='filter_adx',
            field=models.BooleanField(default=False, verbose_name='ADX Filter ✓ (>25)'),
        ),
        migrations.AddField(
            model_name='signal',
            name='filter_volatility',
            field=models.BooleanField(default=False, verbose_name='Volatility Filter ✓'),
        ),
        migrations.AddField(
            model_name='signal',
            name='filter_volume',
            field=models.BooleanField(default=False, verbose_name='Volume Filter ✓'),
        ),
        migrations.AddField(
            model_name='signal',
            name='risk_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='(Entry − SL) / Entry × 100', max_digits=6, null=True, verbose_name='ความเสี่ยง %'),
        ),
        migrations.AddField(
            model_name='signal',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Entry − 1.5 × ATR(14)', max_digits=18, null=True, verbose_name='Stop Loss'),
        ),
        migrations.AddField(
            model_name='signal',
            name='volume_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volume ÷ AvgVol20', max_digits=6, null=True, verbose_name='Volume Ratio'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='macd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='MACD'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='macd_hist',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='MACD Hist'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='macd_signal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='MACD Signal'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='volume_avg30',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Volume Avg 30'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='ราคาเข้า'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='score',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=6, verbose_name='คะแนน 0–100'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='signal_type',
            field=models.CharField(choices=[('GOLDEN_CROSS', 'Golden Cross EMA50/200'), ('EMA_ALIGNMENT', 'EMA Alignment 20>50>200'), ('EMA_PULLBACK', 'EMA Pullback แตะ EMA20'), ('BREAKOUT', 'Breakout เหนือ High 20'), ('BUY', 'ซื้อ'), ('STRONG_BUY', 'ซื้อแข็งแกร่ง'), ('OVERSOLD', 'Oversold RSI<30'), ('DEATH_CROSS', 'Death Cross EMA50/200'), ('BREAKDOWN', 'Breakdown ต่ำกว่า Low 20'), ('SELL', 'ขาย'), ('STRONG_SELL', 'ขายแข็งแกร่ง'), ('OVERBOUGHT', 'Overbought RSI>70'), ('WATCH', 'เฝ้าดู'), ('ALERT', 'แจ้งเตือน')], db_index=True, max_length=20, verbose_name='ประเภทสัญญาณ'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['date', 'adx14'], name='idx_ind_date_adx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['date', 'atr14'], name='idx_ind_date_atr'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['date', 'highest_high_20'], name='idx_ind_date_hh20'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['direction', '-score', '-created_at'], name='idx_sig_direction'),
        ),
    ]
