# Generated by Django 6.0.2 on 2026-03-17 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0003_rename_idx_indicator_symbol_date_desc_idx_ind_symbol_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('FREE', 'สมาชิกฟรี (จำกัดการใช้งาน)'), ('PRO', 'สมาชิก Pro (ฟีเจอร์เต็มรูปแบบ)')], default='FREE', max_length=10, verbose_name='ระดับสมาชิก')),
                ('line_notify_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Line Notify Token')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Chat ID')),
                ('max_strategies', models.IntegerField(default=3, verbose_name='จำนวนสูตรสูงสุด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'โปรไฟล์ผู้ใช้',
                'verbose_name_plural': 'โปรไฟล์ผู้ใช้',
            },
        ),
    ]
