# Generated by Django 6.0.2 on 2026-03-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='ชื่อบริษัท/แบรนด์')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียดธุรกิจ')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='เบอร์โทรศัพท์')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมลติดต่อ')),
                ('line_id', models.CharField(blank=True, max_length=100, verbose_name='Line ID')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('website_url', models.URLField(blank=True, verbose_name='Website URL')),
                ('footer_text', models.CharField(blank=True, max_length=255, verbose_name='ข้อความท้ายเว็บ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'บันทึกโพรไฟล์ธุรกิจ',
                'verbose_name_plural': 'บันทึกโพรไฟล์ธุรกิจ',
            },
        ),
    ]
