# Generated by Django 6.0.2 on 2026-03-17 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_stock_terms(apps, schema_editor):
    StockTerm = apps.get_model("radar", "StockTerm")

    terms = [
        {
            "term": "RSI",
            "category": "indicator",
            "short_definition": "ดัชนีวัดแรงซื้อแรงขาย (0–100) เพื่อดูภาวะซื้อมาก/ขายมาก",
            "full_definition": (
                "RSI (Relative Strength Index) ใช้เปรียบเทียบแรงขึ้นกับแรงลงในช่วงเวลาหนึ่ง (นิยม 14 วัน)\n"
                "- RSI < 30 มักตีความว่า Oversold (ขายมากเกินไป)\n"
                "- RSI > 70 มักตีความว่า Overbought (ซื้อมากเกินไป)\n"
                "ข้อควรระวัง: ในตลาดที่เป็นเทรนด์แรง RSI สามารถค้างเหนือ 70 หรือใต้ 30 ได้นาน ควรใช้ร่วมกับแนวโน้ม (เช่น EMA) และโวลุ่ม"
            ),
            "keywords": ["momentum", "oversold", "overbought", "rsi14", "แรงซื้อ", "แรงขาย"],
            "is_featured": True,
            "priority": 90,
        },
        {
            "term": "EMA",
            "category": "indicator",
            "short_definition": "เส้นค่าเฉลี่ยถ่วงน้ำหนักให้ราคาล่าสุดมากกว่า ใช้ดูแนวโน้ม",
            "full_definition": (
                "EMA (Exponential Moving Average) เป็นค่าเฉลี่ยเคลื่อนที่ที่ให้น้ำหนักกับราคาล่าสุดมากกว่า SMA\n"
                "แนวทางใช้งานที่พบบ่อย:\n"
                "- EMA20: ระยะสั้น\n"
                "- EMA50: ระยะกลาง\n"
                "- EMA200: ระยะยาว\n"
                "สัญญาณยอดนิยม:\n"
                "- Golden Cross: EMA50 ตัด EMA200 ขึ้น (เชิงบวก)\n"
                "- Death Cross: EMA50 ตัด EMA200 ลง (เชิงลบ)"
            ),
            "keywords": ["trend", "moving average", "ema20", "ema50", "ema200", "golden cross", "death cross"],
            "is_featured": True,
            "priority": 90,
        },
        {
            "term": "MACD",
            "category": "indicator",
            "short_definition": "ตัวชี้วัดแนวโน้ม/โมเมนตัมจากความต่างของ EMA ใช้ดูจังหวะเปลี่ยนเทรนด์",
            "full_definition": (
                "MACD (Moving Average Convergence Divergence) = EMA(12) - EMA(26)\n"
                "มักใช้ร่วมกับเส้น Signal (EMA 9 ของ MACD)\n"
                "สัญญาณยอดนิยม:\n"
                "- MACD ตัด Signal ขึ้น: โมเมนตัมเริ่มดีขึ้น\n"
                "- MACD ตัด Signal ลง: โมเมนตัมเริ่มอ่อนลง\n"
                "- Histogram เปลี่ยนจากลบเป็นบวก: แรงเริ่มกลับทาง\n"
                "ข้อควรระวัง: ในตลาด Sideway จะเกิดสัญญาณหลอกบ่อย ควรใช้กับตัวกรองเทรนด์"
            ),
            "keywords": ["trend", "momentum", "histogram", "signal line", "macd12", "macd26", "macd9"],
            "is_featured": True,
            "priority": 85,
        },
        {
            "term": "BB",
            "category": "indicator",
            "short_definition": "Bollinger Bands ใช้ดูกรอบความผันผวนและภาวะราคาแพง/ถูกเทียบค่าเฉลี่ย",
            "full_definition": (
                "Bollinger Bands ประกอบด้วยเส้นกลาง (SMA20) และเส้นบน/ล่าง (± 2 ส่วนเบี่ยงเบนมาตรฐาน)\n"
                "แนวทางใช้งาน:\n"
                "- ราคาแตะ/หลุด Band บน: โมเมนตัมแรง (ไม่จำเป็นต้องแปลว่า Overbought ทันที)\n"
                "- ราคาแตะ Band ล่าง: อ่อนแรง/อาจเด้ง\n"
                "- Band แคบ: ความผันผวนต่ำ (มีโอกาสเกิดการ Breakout)\n"
                "- Band กว้าง: ความผันผวนสูง (ระวังการแกว่งแรง)"
            ),
            "keywords": ["bollinger", "volatility", "sma20", "stddev", "band"],
            "is_featured": True,
            "priority": 70,
        },
        {
            "term": "ATR",
            "category": "indicator",
            "short_definition": "Average True Range วัดความผันผวน ใช้กำหนด Stop Loss/Position Sizing",
            "full_definition": (
                "ATR (Average True Range) วัดความผันผวนจาก True Range แล้วทำค่าเฉลี่ย (นิยม 14)\n"
                "แนวทางใช้งาน:\n"
                "- ตั้ง Stop Loss แบบ ATR: SL = Entry - (k * ATR) เช่น k=1.5\n"
                "- เลือกขนาดการลงทุนให้เหมาะกับความผันผวน: หุ้น ATR สูงควรลดขนาดสถานะ"
            ),
            "keywords": ["volatility", "risk", "stop loss", "position sizing", "atr14"],
            "is_featured": True,
            "priority": 70,
        },
        {
            "term": "ADX",
            "category": "indicator",
            "short_definition": "วัดความแข็งแกร่งของแนวโน้ม (ไม่บอกทิศทาง) มักใช้ค่ามากกว่า 25",
            "full_definition": (
                "ADX (Average Directional Index) วัดความแรงของเทรนด์จาก +DI และ -DI\n"
                "แนวทางใช้งาน:\n"
                "- ADX > 25: แนวโน้มชัด\n"
                "- +DI > -DI: เทรนด์ขาขึ้นเด่น\n"
                "- -DI > +DI: เทรนด์ขาลงเด่น\n"
                "ข้อควรระวัง: ADX บอกความแรง ไม่ได้บอกว่า Long หรือ Short ต้องดู DI และโครงสร้างราคา"
            ),
            "keywords": ["trend strength", "di+", "di-", "adx14"],
            "is_featured": True,
            "priority": 65,
        },
        {
            "term": "HH20/LL20",
            "category": "concept",
            "short_definition": "Highest High 20 / Lowest Low 20 ใช้หา Breakout/Breakdown",
            "full_definition": (
                "HH20 คือราคาสูงสุดใน 20 วัน, LL20 คือราคาต่ำสุดใน 20 วัน\n"
                "แนวทางใช้งาน:\n"
                "- Breakout: ปิดเหนือ HH20 (มักต้องการ Volume สนับสนุน)\n"
                "- Breakdown: ปิดต่ำกว่า LL20\n"
                "เหมาะกับกลยุทธ์ตามเทรนด์ และควรมีการจัดการความเสี่ยง เช่น ATR Stop"
            ),
            "keywords": ["breakout", "breakdown", "highest high", "lowest low", "20 days", "แนวต้าน", "แนวรับ"],
            "is_featured": True,
            "priority": 60,
        },
        {
            "term": "LONGTERM-SHORTTERM",
            "category": "faq",
            "short_definition": "การตั้งค่า LongTerm/ShortTerm ช่วยแยกบริบทเทรนด์ใหญ่กับจังหวะเข้าออก",
            "full_definition": (
                "เหตุผลที่นิยมแยก LongTerm กับ ShortTerm:\n"
                "1) LongTerm ใช้ระบุแนวโน้มหลัก (บริบท) เช่น EMA200 หรือโครงสร้าง Higher High\n"
                "2) ShortTerm ใช้หาจังหวะเข้าออก เช่น EMA20/RSI/Breakout ระยะสั้น\n"
                "ประโยชน์:\n"
                "- ลดสัญญาณหลอก: เทรดตามทิศทางเทรนด์หลักก่อน\n"
                "- เข้าง่ายขึ้น: รอจังหวะย่อ/เบรกที่เหมาะสมแทนการไล่ราคา\n"
                "ตัวอย่าง:\n"
                "- เทรนด์ขาขึ้น (LongTerm): ราคาอยู่เหนือ EMA200\n"
                "- จังหวะเข้า (ShortTerm): ย่อแตะ EMA20 แล้วเด้ง หรือ Breakout เหนือ HH20"
            ),
            "keywords": ["longterm", "shortterm", "ระยะยาว", "ระยะสั้น", "บริบท", "จังหวะเข้า", "ทำไมต้องเลือก longterm-shortterm"],
            "is_featured": True,
            "priority": 80,
        },
    ]

    for t in terms:
        term_key = (t["term"] or "").strip().upper()
        StockTerm.objects.update_or_create(
            term=term_key,
            defaults={
                "short_definition": t["short_definition"],
                "full_definition": t["full_definition"],
                "category": t["category"],
                "keywords": t["keywords"],
                "is_featured": t["is_featured"],
                "priority": t["priority"],
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0005_businessprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='คำศัพท์/หัวข้อ')),
                ('short_definition', models.TextField(blank=True, verbose_name='คำอธิบายสั้น')),
                ('full_definition', models.TextField(blank=True, verbose_name='คำอธิบายเต็ม')),
                ('category', models.CharField(choices=[('indicator', 'Indicator'), ('pattern', 'Pattern'), ('concept', 'Concept'), ('faq', 'FAQ'), ('other', 'Other')], db_index=True, default='other', max_length=24, verbose_name='หมวดหมู่')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='คีย์เวิร์ด')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='แนะนำ (Featured)')),
                ('priority', models.IntegerField(db_index=True, default=0, verbose_name='ลำดับความสำคัญ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'คลังคำศัพท์/คำแนะนำ',
                'verbose_name_plural': 'คลังคำศัพท์/คำแนะนำ',
                'ordering': ['-is_featured', '-priority', 'term'],
                'indexes': [models.Index(fields=['category', '-is_featured', '-priority'], name='idx_term_cat_feat_pri'), models.Index(fields=['term'], name='idx_term_term')],
            },
        ),
        migrations.CreateModel(
            name='TermQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='คำถาม')),
                ('normalized_term', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='คำศัพท์ที่เกี่ยวข้อง')),
                ('status', models.CharField(choices=[('NEW', 'รอคำตอบ'), ('ANSWERED', 'ตอบแล้ว')], db_index=True, default='NEW', max_length=16, verbose_name='สถานะ')),
                ('answer_short', models.TextField(blank=True, verbose_name='คำตอบสั้น')),
                ('answer_full', models.TextField(blank=True, verbose_name='คำตอบเต็ม')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่ตอบ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_term_questions', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ตอบ')),
                ('asked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='term_questions', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ถาม')),
            ],
            options={
                'verbose_name': 'คำถามคำศัพท์',
                'verbose_name_plural': 'คำถามคำศัพท์',
                'ordering': ['status', '-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='idx_termq_status_recent'), models.Index(fields=['normalized_term', '-created_at'], name='idx_termq_term_recent')],
            },
        ),
        migrations.RunPython(seed_stock_terms, migrations.RunPython.noop),
    ]
