# Generated by Django 6.0.2 on 2026-03-17 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0006_stockterm_termquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('market_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pnl_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('rsi14', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ema20', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('ema50', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('ema200', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('adx14', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('decision', models.CharField(choices=[('BUY_MORE', 'Buy More'), ('HOLD', 'Hold'), ('SELL', 'Sell')], max_length=16)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('explanation', models.TextField()),
                ('signals', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_analyses', to='radar.symbol')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'วิเคราะห์สถานะถือหุ้น',
                'verbose_name_plural': 'วิเคราะห์สถานะถือหุ้น',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', '-created_at'], name='idx_pos_symbol_recent'), models.Index(fields=['user', '-created_at'], name='idx_pos_user_recent')],
            },
        ),
    ]
