# Generated by Django 5.0 on 2026-03-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0007_positionanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='หัวข้อ')),
                ('summary', models.TextField(blank=True, verbose_name='สรุปข่าว')),
                ('url', models.URLField(max_length=1024, unique=True, verbose_name='ลิงก์ข่าว')),
                ('source', models.CharField(choices=[('SET', 'SET (ตลาดหลักทรัพย์)'), ('REUTERS', 'Reuters'), ('YAHOO', 'Yahoo Finance'), ('GOOGLE', 'Google News'), ('THANSETTAKIJ', 'ฐานเศรษฐกิจ'), ('MANAGER', 'ผู้จัดการออนไลน์'), ('BANGKOKPOST', 'Bangkok Post'), ('OTHER', 'อื่นๆ')], db_index=True, default='OTHER', max_length=20, verbose_name='แหล่งข่าว')),
                ('published_at', models.DateTimeField(db_index=True, verbose_name='เวลาเผยแพร่')),
                ('sentiment', models.CharField(choices=[('BULLISH', '🟢 Bullish'), ('BEARISH', '🔴 Bearish'), ('NEUTRAL', '⚪ Neutral')], db_index=True, default='NEUTRAL', max_length=10, verbose_name='Sentiment')),
                ('sentiment_score', models.FloatField(default=0.0, help_text='-1.0 (Bearish) ถึง +1.0 (Bullish)', verbose_name='คะแนน Sentiment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbols', models.ManyToManyField(blank=True, related_name='news', to='radar.symbol', verbose_name='หุ้นที่เกี่ยวข้อง')),
            ],
            options={
                'verbose_name': 'ข่าวหุ้น',
                'verbose_name_plural': 'ข่าวหุ้น',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='idx_news_pub'), models.Index(fields=['source', '-published_at'], name='idx_news_src_pub'), models.Index(fields=['sentiment', '-published_at'], name='idx_news_sent_pub')],
            },
        ),
    ]
