# Generated by Django 5.0 on 2026-03-22 01:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0008_newsitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watchlist',
                'verbose_name_plural': 'Watchlists',
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='หมายเหตุ')),
                ('alert_price_high', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Alert ราคาสูงกว่า')),
                ('alert_price_low', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Alert ราคาต่ำกว่า')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='radar.symbol')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='radar.watchlist')),
            ],
            options={
                'verbose_name': 'Watchlist Item',
                'verbose_name_plural': 'Watchlist Items',
                'ordering': ['created_at'],
                'unique_together': {('watchlist', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='WatchlistTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BUY', 'ซื้อ'), ('SELL', 'ขาย')], default='BUY', max_length=4, verbose_name='ซื้อ/ขาย')),
                ('price', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='ราคาต่อหน่วย')),
                ('quantity', models.IntegerField(verbose_name='จำนวนหุ้น')),
                ('trade_date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่ทำรายการ')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='radar.watchlistitem')),
            ],
            options={
                'verbose_name': 'รายการซื้อขาย',
                'verbose_name_plural': 'รายการซื้อขาย',
                'ordering': ['trade_date', 'created_at'],
            },
        ),
    ]
