# Generated by Django 5.0 on 2026-03-23 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0009_watchlist_watchlistitem_watchlisttrade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ชื่อแผน')),
                ('tier', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('PREMIUM', 'Premium')], max_length=10, verbose_name='ระดับ')),
                ('price_thb', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคา (บาท/เดือน)')),
                ('duration_days', models.IntegerField(default=30, verbose_name='ระยะเวลา (วัน)')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='ฟีเจอร์ (JSON list)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'แผนสมาชิก',
                'verbose_name_plural': 'แผนสมาชิก',
                'ordering': ['price_thb'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='line_notify_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_strategies',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tier',
            field=models.CharField(choices=[('FREE', 'Free — ทดลองใช้'), ('PRO', 'Pro — ฟีเจอร์เต็ม'), ('PREMIUM', 'Premium — ไม่จำกัด')], db_index=True, default='FREE', max_length=10, verbose_name='ระดับสมาชิก'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'กำลังใช้งาน'), ('EXPIRED', 'หมดอายุ'), ('CANCELLED', 'ยกเลิก'), ('TRIAL', 'ทดลองใช้')], db_index=True, default='ACTIVE', max_length=10, verbose_name='สถานะ')),
                ('start_date', models.DateField(verbose_name='วันเริ่ม')),
                ('end_date', models.DateField(db_index=True, verbose_name='วันสิ้นสุด')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('payment_ref', models.CharField(blank=True, max_length=255, verbose_name='หมายเลขอ้างอิงการชำระ')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ (admin)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย admin')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='radar.profile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='radar.subscriptionplan', verbose_name='แผน')),
            ],
            options={
                'verbose_name': 'ประวัติสมาชิก',
                'verbose_name_plural': 'ประวัติสมาชิก',
                'ordering': ['-start_date'],
            },
        ),
    ]
