# Generated by Django 5.0 on 2026-03-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0010_subscription_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Google ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='login_via_google',
            field=models.BooleanField(db_index=True, default=False, verbose_name='สมัครด้วย Google'),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='รูปโปรไฟล์ Google'),
        ),
    ]
