# Generated by Django 5.0 on 2026-03-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0012_latest_snapshot_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestSnapshot',
            fields=[
                ('symbol_id', models.IntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('exchange', models.CharField(max_length=20)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('price_date', models.DateField(null=True)),
                ('close', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('high', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('low', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('volume', models.BigIntegerField(null=True)),
                ('ema20', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('ema50', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('ema200', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('rsi', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('macd', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('macd_signal', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('macd_hist', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('adx14', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('atr14', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('bb_upper', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('bb_lower', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('highest_high_20', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('lowest_low_20', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('volume_avg20', models.BigIntegerField(null=True)),
                ('signal_type', models.CharField(max_length=20, null=True)),
                ('direction', models.CharField(max_length=10, null=True)),
                ('signal_score', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('stop_loss', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('risk_pct', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('signal_date', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Latest Snapshot',
                'verbose_name_plural': 'Latest Snapshots',
                'db_table': 'radar_latest_snapshot',
                'ordering': ['-signal_score'],
                'managed': False,
            },
        ),
    ]
