# Generated by Django 5.0 on 2026-03-27 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0013_latestsnapshot'),
        ('radar', '0013_newsitem_url_max_length_2048'),
    ]

    operations = [
    ]
